name: publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: cp README.md LICENSE-APACHE LICENSE-MIT compiler/cli/
      - run: uv build
        working-directory: compiler/cli
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: compiler/cli/dist
